export {
  DEPARTMENT as DEPARTMENT,
  EMPLOYEE as EMPLOYEE,
  NUMBER_OF_PAGINATION as NUMBER_OF_PAGINATION,
  DEFAULT_PAGE_SIZE as DEFAULT_PAGE_SIZE,
  DEFAULT_PAGE_NUMBER as DEFAULT_PAGE_NUMBER,
} from './constants';
